[build]
publish = "docs/.vitepress/dist"
command = "pnpm run docs:build"

[context.deploy-preview]
ignore = "exit 0"

[context.branch-deploy]
ignore = "exit 0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
