name: Release Preversion

on:
  push:
    tags:
      # only run for versions that have -something appended
      - 'v[0-9]+.[0-9]+.[0-9]+-**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
